# Generated by Django 5.2.6 on 2026-07-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UpsPluginSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Solange aus, überwacht dieses Plugin nichts und kann nichts auslösen.",
                    ),
                ),
                (
                    "check_kind",
                    models.CharField(
                        choices=[
                            (
                                "always_on",
                                "Immer eingeschaltet (Testmodus - löst nie aus)",
                            ),
                            ("gpio", "GPIO-Pin (Raspberry Pi, RPi.GPIO)"),
                            ("command", "Eigenes Kommando"),
                        ],
                        default="always_on",
                        max_length=20,
                    ),
                ),
                (
                    "gpio_pin",
                    models.IntegerField(
                        default=17, help_text="BCM-Pin-Nummer, nur für 'GPIO-Pin'."
                    ),
                ),
                (
                    "gpio_active_low",
                    models.BooleanField(
                        default=True,
                        help_text="An = Pin ist LOW (häufigste Beschaltung mit Pull-up). Aus, wenn dein Board das umgekehrt macht.",
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Shell-Kommando, nur für 'Eigenes Kommando'. Exit-Code 0 = Strom vorhanden, ungleich 0 = Stromausfall - so lässt sich jedes Hersteller-CLI-Tool (PiJuice, Geekworm, ...) einbinden, ohne dass dieses Plugin es selbst kennen muss.",
                        max_length=512,
                    ),
                ),
                (
                    "poll_interval_s",
                    models.IntegerField(
                        default=5, help_text="Wie oft der Status geprüft wird."
                    ),
                ),
                (
                    "grace_period_s",
                    models.IntegerField(
                        default=30,
                        help_text="Wie lange nach einem erkannten Stromausfall gewartet wird, bevor die Shutdown-Sequenz startet - kehrt der Strom in dieser Zeit zurück (kurzes Flackern), wird nichts ausgelöst.",
                    ),
                ),
                (
                    "job_wait_timeout_s",
                    models.IntegerField(
                        default=120,
                        help_text="Maximale Wartezeit auf eine sauber stoppende Aufnahme und laufende Hintergrund-Jobs (MP3-Konvertierung, Song-Export, Wiedergabe-Vorbereitung), bevor trotzdem heruntergefahren wird.",
                    ),
                ),
                (
                    "shutdown_command",
                    models.CharField(
                        default="sudo shutdown -h now",
                        help_text="Läuft am Ende der Sequenz. Für Tests hierhin ein harmloses Kommando eintragen (z.B. 'echo shutdown-would-fire-here') statt des echten Shutdowns.",
                        max_length=200,
                    ),
                ),
                (
                    "last_power_status",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
