# Generated by Django 5.2.6 on 2026-07-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("x32_recorder_ups_plugin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upspluginsettings",
            name="check_kind",
            field=models.CharField(
                choices=[
                    ("always_on", "Immer eingeschaltet (Testmodus - löst nie aus)"),
                    ("gpio", "GPIO-Pin (Raspberry Pi, RPi.GPIO)"),
                    ("command", "Eigenes Kommando"),
                ],
                default="always_on",
                max_length=20,
                verbose_name="Erkennungsart",
            ),
        ),
        migrations.AlterField(
            model_name="upspluginsettings",
            name="command",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Shell-Kommando, nur für 'Eigenes Kommando'. Exit-Code 0 = Strom vorhanden, ungleich 0 = Stromausfall - so lässt sich jedes Hersteller-CLI-Tool (PiJuice, Geekworm, ...) einbinden, ohne dass dieses Plugin es selbst kennen muss.",
                max_length=512,
                verbose_name="Eigenes Kommando",
            ),
        ),
        migrations.AlterField(
            model_name="upspluginsettings",
            name="enabled",
            field=models.BooleanField(
                default=False,
                help_text="Solange aus, überwacht dieses Plugin nichts und kann nichts auslösen.",
                verbose_name="Aktiviert",
            ),
        ),
        migrations.AlterField(
            model_name="upspluginsettings",
            name="gpio_active_low",
            field=models.BooleanField(
                default=True,
                help_text="An = Pin ist LOW (häufigste Beschaltung mit Pull-up). Aus, wenn dein Board das umgekehrt macht.",
                verbose_name="Aktiv bei LOW",
            ),
        ),
        migrations.AlterField(
            model_name="upspluginsettings",
            name="gpio_pin",
            field=models.IntegerField(
                default=17,
                help_text="BCM-Pin-Nummer, nur für 'GPIO-Pin'.",
                verbose_name="GPIO-Pin (BCM)",
            ),
        ),
        migrations.AlterField(
            model_name="upspluginsettings",
            name="grace_period_s",
            field=models.IntegerField(
                default=30,
                help_text="Wie lange nach einem erkannten Stromausfall gewartet wird, bevor die Shutdown-Sequenz startet - kehrt der Strom in dieser Zeit zurück (kurzes Flackern), wird nichts ausgelöst.",
                verbose_name="Gnadenfrist (s)",
            ),
        ),
        migrations.AlterField(
            model_name="upspluginsettings",
            name="job_wait_timeout_s",
            field=models.IntegerField(
                default=120,
                help_text="Maximale Wartezeit auf eine sauber stoppende Aufnahme und laufende Hintergrund-Jobs (MP3-Konvertierung, Song-Export, Wiedergabe-Vorbereitung), bevor trotzdem heruntergefahren wird.",
                verbose_name="Job-Wartezeit (s)",
            ),
        ),
        migrations.AlterField(
            model_name="upspluginsettings",
            name="last_checked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Zuletzt geprüft"
            ),
        ),
        migrations.AlterField(
            model_name="upspluginsettings",
            name="last_power_status",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Letzter Status"
            ),
        ),
        migrations.AlterField(
            model_name="upspluginsettings",
            name="poll_interval_s",
            field=models.IntegerField(
                default=5,
                help_text="Wie oft der Status geprüft wird.",
                verbose_name="Prüfintervall (s)",
            ),
        ),
        migrations.AlterField(
            model_name="upspluginsettings",
            name="shutdown_command",
            field=models.CharField(
                default="sudo shutdown -h now",
                help_text="Läuft am Ende der Sequenz. Für Tests hierhin ein harmloses Kommando eintragen (z.B. 'echo shutdown-would-fire-here') statt des echten Shutdowns.",
                max_length=200,
                verbose_name="Shutdown-Kommando",
            ),
        ),
    ]
